-- ==============================================================================
-- DKHP UIT - SUPABASE DATABASE ROW LEVEL SECURITY (RLS) & ACCESS CONTROL SETUP
-- Chạy đoạn mã này trong Supabase Dashboard -> SQL Editor để khóa bảo mật 100%
-- ==============================================================================

-- 1. Đảm bảo bảng uit_teacher_reviews tồn tại và có các ràng buộc chặt chẽ
CREATE TABLE IF NOT EXISTS public.uit_teacher_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  teacher_name VARCHAR(120) NOT NULL,
  course_name VARCHAR(120) NOT NULL,
  semester_name VARCHAR(50) DEFAULT 'HK2 2025-2026',
  rating SMALLINT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  grading VARCHAR(50) DEFAULT 'Chuẩn chỉ / Công bằng',
  attendance VARCHAR(50) DEFAULT 'Bình thường',
  workload VARCHAR(50) DEFAULT 'Vừa sức',
  tags TEXT[] DEFAULT '{}',
  review_text TEXT NOT NULL CHECK (length(trim(review_text)) >= 5 AND length(review_text) <= 2500),
  posvotes INT DEFAULT 1 CHECK (posvotes >= 0)
);

-- 2. Đặt Index tăng tốc độ truy vấn theo tên giảng viên và thời gian
CREATE INDEX IF NOT EXISTS idx_reviews_teacher_name ON public.uit_teacher_reviews (teacher_name);
CREATE INDEX IF NOT EXISTS idx_reviews_created_at ON public.uit_teacher_reviews (created_at DESC);

-- 3. BẬT ROW LEVEL SECURITY (RLS) - BẮT BUỘC ĐỂ BẢO VỆ DATABASE
ALTER TABLE public.uit_teacher_reviews ENABLE ROW LEVEL SECURITY;

-- 4. XÓA CÁC POLICY CŨ NẾU CÓ ĐỂ TRÁNH XUNG ĐỘT
DROP POLICY IF EXISTS "Public can view reviews" ON public.uit_teacher_reviews;
DROP POLICY IF EXISTS "Public can insert valid reviews" ON public.uit_teacher_reviews;
DROP POLICY IF EXISTS "Deny anonymous updates" ON public.uit_teacher_reviews;
DROP POLICY IF EXISTS "Deny anonymous deletes" ON public.uit_teacher_reviews;

-- 5. POLICY 1: CHO PHÉP MỌI NGƯỜI (ANON) ĐỌC REVIEW CÔNG KHAI
CREATE POLICY "Public can view reviews" 
ON public.uit_teacher_reviews
FOR SELECT 
TO anon, authenticated
USING (true);

-- 6. POLICY 2: CHO PHÉP GỬI REVIEW MỚI NHƯNG PHẢI THỎA MÃN VALIDATION CHẶT CHẼ
CREATE POLICY "Public can insert valid reviews" 
ON public.uit_teacher_reviews
FOR INSERT 
TO anon, authenticated
WITH CHECK (
  length(trim(teacher_name)) >= 2 AND length(teacher_name) <= 120 AND
  length(trim(course_name)) >= 2 AND length(course_name) <= 120 AND
  length(trim(review_text)) >= 5 AND length(review_text) <= 2500 AND
  rating >= 1 AND rating <= 5
);

-- 7. KHÔNG CẤP POLICY UPDATE & DELETE CHO ANON
-- Mặc định RLS sẽ CHẶN 100% các request UPDATE & DELETE từ anonKey
-- Chỉ tài khoản Admin đăng nhập bằng Supabase Dashboard mới có quyền sửa/xóa.
